#ifndef DEFAULTSETTINGS_H
#define DEFAULTSETTINGS_H


#define DEFAULT_SETTINGS_VALUE_TRACER_VISIBLE                   false
#define DEFAULT_SETTINGS_VALUE_BORDER_VISIBLE                   true
#define DEFAULT_SETTINGS_VALUE_COMPONENT_NAMES_VISIBLE          true
#define DEFAULT_SETTINGS_VALUE_DASHBOARD_VISIBLE                true
#define DEFAULT_SETTINGS_VALUE_CLIP_COMPONENT_ROOT              true
#define DEFAULT_SETTINGS_VALUE_SLOW_MOTION                      false

#define DEFAULT_SETTINGS_VALUE_MAIN_WINDOW_STATE                Qt::WindowNoState

#define DEFAULT_SETTINGS_VALUE_DESIGNER_MODE                    "Developer"

#define DEFAULT_SETTINGS_VALUE_PROJECT_PANE_STICKY              true

#define DEFAULT_SETTINGS_VALUE_PROJECT_PANE_WIDTH               360
#define DEFAULT_SETTINGS_VALUE_PROJECT_PANE_HEIGHT              600

#define DEFAULT_SETTINGS_VALUE_PROPERTIES_PANE_STICKY           true

#define DEFAULT_SETTINGS_VALUE_PROPERTIES_PANE_WIDTH            360
#define DEFAULT_SETTINGS_VALUE_PROPERTIES_PANE_HEIGHT           600


#define DEFAULT_SETTINGS_VALUE_EDITOR_SYNTAX_HIGHLIGHT          true
#define DEFAULT_SETTINGS_VALUE_EDITOR_SHOW_LINE_NUMBERS         true
#define DEFAULT_SETTINGS_VALUE_EDITOR_FONT_SIZE                 12



#endif // DEFAULTSETTINGS_H
